[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "../netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200